[features]
resolution = true
seeds = true
skip-lint = false

[programs.localnet]
sss_core = "E5T7B4F3kZhTPaiso7LDdNo2p3Z66qbqfJvZ1rosZuTs"
sss_transfer_hook = "Z6XbtKYyRLYJDogwXUmWti3v28ws98bKE1Mo9DvZs4c"

[programs.devnet]
sss_core = "E5T7B4F3kZhTPaiso7LDdNo2p3Z66qbqfJvZ1rosZuTs"
sss_transfer_hook = "Z6XbtKYyRLYJDogwXUmWti3v28ws98bKE1Mo9DvZs4c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
url = "https://api.devnet.solana.com"
